### PR TITLE
Migrate to Microsoft.Extensions.Logging

### PR DESCRIPTION
**Pull request by zmckinnon**
Addresses #98.

### CODE REVIEW

**Comment by PHeonix25** [comment]
LGTM! 👍 

Thanks @zmckinnon. I'll leave it up to @Workshop2 to approve+merge it.

**Comment by zmckinnon** [comment]
@Workshop2, are you accepting PRs?  I am using noobot on a project I am working on and I was hoping to address #99 & #100 too.

I can update documentation and do a major version bump if you'd like.  Just let me know.

**Comment by Workshop2** [comment]
Hi all, I will review it tomorrow and get back to you 👍

**Comment by johnkors** [comment]
It would be nice to move to using the .NET Core DI model as well: 

* Microsoft.Extensions.Configuration.Abstractions
* Resolving Middlewares from DI

Today, we cannot inject dependencies into middleware.

**Review by Workshop2 — APPROVED** [review]

**Comment by Workshop2** [comment]
Thanks @zmckinnon

**Pull request merged**
